---
- name: Gather data about target box
  hosts: dbservers
  gather_facts: yes
  tasks:
    - debug: Gather Facts
    
- name: Configure target box
  hosts: dbservers
  sudo: yes
  roles:
    - { role: ubuntu }
    - { role: mysql }
    - { role: postgres }