---
# file: staticwebservers.yml
- name: Gather data about target box
  hosts: webservers
  gather_facts: yes
  tasks:
    - debug: Gather Facts
    
- name: Configure target box
  hosts: webservers
  sudo: yes
  roles:
    - { role: ubuntu }
    - { role: staticapp }
    - { role: nginx }
    