---

- name: Gather data about local development box
  hosts: vagrant
  gather_facts: yes
  tasks:
    - debug: Gather Facts

- name: Configure development box
  hosts: vagrant
  sudo: yes
  roles:
    - { role: mysql }
        
- name: Configure development box
  hosts: vagrant
  sudo: yes
  roles:
    - { role: ubuntu }
    - { role: mailcatcher }
    - { role: django_dev }
    