---
- name: StaticApp | Packages | Install required system packages.
  apt: >
    pkg={{ item }}
    state=installed
    update-cache=yes
    cache_valid_time=3600
  with_items:
    - build-essential
  tags:
    - base
    - packages
    - provision
    - app
