---
- name: Project | Drupal | Generate drupal settings file.
  notify:  
    - restart nginx
    - restart php5-fpm
  template: >
    src=drupal_settings.php.j2
    dest="{{ drupal.root }}/sites/default/settings.php"
  tags:
    - configuration
    - drupalsettings
    - drupal
    - webserver
    - update
  