---
- name: PostgreSQL | Install Packages
  apt: >
    pkg={{ item }}
    state=installed
    update-cache=yes
    cache_valid_time=3600
  with_items:
    - build-essential
    - postgresql
    - python-dev
    - python-setuptools
    - python-psycopg2
    - postgresql-9.3
    - postgresql-contrib-9.3
    - postgresql-doc-9.3
    - postgresql-server-dev-all
    - libpq-dev

# make sure service is enabled on boot and restart
- name: PostgreSQL| Restart
  service: name=postgresql state=restarted enabled=yes
  sudo: yes
