---
- name: Nginx | Install required system packages.
  apt: >
    pkg={{ item }}
    state=installed
    update-cache=yes
    cache_valid_time=3600
  with_items:
    - build-essential
    - nginx
  tags:
    - nginx
    - packages
    - provision
    - webserver