---
- name: Nginx | remove default nginx site
  notify: restart nginx
  file: >
    path=/etc/nginx/sites-enabled/default
    state=absent

- name: Nginx | Install nginx configuration file.
  notify: restart nginx
  template: >
    src="vhost.{{ nginx.conf_type }}.conf.j2"
    dest="/etc/nginx/sites-enabled/{{ project.name }}.conf"
  tags:
    - configuration
    - nginx
    - webserver
    - update

