---
- name: uWsgi | (apt) Install required system packages.
  sudo: yes
  sudo_user: root
  apt: >
    pkg={{ item }}
    state=installed
    update-cache=yes
  with_items:
    - build-essential
    - python-dev
    - python-setuptools
    - python-virtualenv
    - python-pip
  tags:
    - packages
    - provision
    - uwsgi

- name: uWsgi | (pip) Install required system packages.
  sudo_user: "{{ project.user }}"
  pip: >
    name={{ item }} 
    virtualenv="{{ project.virtualenv }}"
  with_items:
    - uwsgi
  tags:
    - packages
    - provision
    - uwsgi