---

- name: MySQL | Create MySQL configuration file.
  sudo: yes
  template: >
    src=mysql.my.cnf.j2
    dest=/etc/my.cnf
  notify:
    - restart mysql
  tags: 
    - mysql
    - database

- name: MySQL | Change main settings for bind-address.
  sudo: yes
  lineinfile: >
    dest=/etc/mysql/my.cnf
    regexp="^bind-address"
    insertafter="bind-address"
    line="#bind-address"
  notify:
    - restart mysql
  tags: 
    - mysql
    - database


## TEST
#- name: MySQL | TEST restart.
#  service: >
#    name=mysql
#    state=restarted
#    

# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: MySQL | Set the root password.
  sudo: yes
  mysql_user: >
    name=root 
    host={{ item }} 
    password={{ mysql.root_password }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: true
  tags: 
    - mysql
    - database

- name: MySQL | Config for easy access as root user.
  template: >
    src=mysql_root.my.cnf.j2
    dest=/root/.my.cnf
    owner=root
    mode=0600
  tags: 
    - mysql
    - database

- name: MySQL | Create application database.
  mysql_db: >
    name={{ database.name }}
    collation="{{ mysql.collation | default('utf8_general_ci') }}"
    encoding="{{ mysql.encoding | default('utf8') }}"
    state=present 
    login_password={{ mysql.root_password }} 
    login_user=root
  tags: 
    - mysql
    - database

- name: MySQL | Create application database user.
  mysql_user: >
    name={{ database.user }} 
    password={{ database.password }} 
    priv={{ database.name }}.*:ALL
    host='%'
    state=present 
    login_password={{ mysql.root_password }} 
    login_user=root
  tags: 
    - mysql
    - database
