---
- name: PHP5 | Install required system packages.
  apt: >
    pkg={{ item }}
    state=installed
    update-cache=yes
    cache_valid_time=3600
  with_items:
    - php5
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-mysqlnd
    - php5-memcached
    - php5-imagick
    - php5-xcache
    - php-pear
  tags:
    - packages
    - provision
    - webserver
    - php
    