---
- name: restart uwsgi
  sudo_user: root
  service: >
    name="{{ project.name }}-uwsgi"
    state=restarted
    enabled=yes
    
- name: reload uwsgi
  sudo_user: root
  service: >
    name="{{ project.name }}-uwsgi"
    state=restarted
    enabled=yes