---
- name: DjangoApp | App | Set up cron jobs.
  cron: >
    name="{{ project.name }}-clear-old-sessions"
    user={{ project.user }} 
    job="{{ item }}" 
    state=present
  with_template:
    - ../templates/clear_sessions.j2
  tags:
    - cron
    - app
    