---
- name: DjangoApp | Packages | Install required system packages.
  apt: >
    pkg={{ item }}
    state=installed
    update-cache=yes
    cache_valid_time=3600
  with_items:
    - build-essential
    - git
    - python-dev
    - python-setuptools
    - python-virtualenv
    - python-pip
    - libpq-dev
    - imagemagick
  tags:
    - base
    - packages
    - provision
    - app
